<a href="https://colab.research.google.com/github/Varqina/BasicCoursePython/blob/master/01_wprowadzenie/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra Liniowa

Norma wektorowa

In [4]:
import numpy as np
v1 = np.array([-6,4])
v1

array([-6,  4])

In [5]:
np.linalg.norm(v1) # dlugosc wektora 

7.211102550927978

In [7]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odleglosc dwoch punktow na plaszczyznie


In [8]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

Mnozenie maciezy

In [11]:
x = np.array([[5,3],[3,9]])
y = np.array([[1],[-1]])
print(x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [14]:
z = np.dot(x,y)
z

array([[ 2],
       [-6]])

In [16]:
z.shape

(2, 1)

In [18]:
x = np.array([[2, -1, 3],
              [3,1,0]])
y = np.array([[2,1,-1],
              [0, -1,2],
              [3, 2, 0]])
z = np.dot(x,y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [19]:
z.shape

(2, 3)

Wyznacznik maciezy (a11a22-a12a21)


In [21]:
A = np.array([[2, 4], [-1,3]])
round(np.linalg.det(A))

10

Slad Macierzy, suma wartoci na przekatnej

In [22]:
np.trace(A)

5

Macierz jednostkowa, macierz kwadratowa
jedynki na przekatnej 

In [23]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna, macierz kwadratowa. A*B = B*a = macierz jednostkowa

In [26]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [28]:
np.set_printoptions(precision=4, suppress=True)
A.dot(B)

array([[1., 0.],
       [0., 1.]])

In [29]:
B.dot(A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana. Zamiania wierszy na columny

In [30]:
C = np.array([[1,2,3],
          [2,3,4]])


In [31]:
C.T

array([[1, 2],
       [2, 3],
       [3, 4]])

Uklady rownan

rowanie 2x+4y = 10

x - y = -1


In [38]:
A = np.array([[2,4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [42]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [44]:
np.around(0)
a_inv = np.linalg.inv(A)
np.dot(a_inv, B)

array([[1.],
       [2.]])