<a href="https://colab.research.google.com/github/Varqina/BasicCoursePython/blob/master/01_wprowadzenie/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

1D Array

In [ ]:
x = np.array([1,3])
x 

array([1, 3])

In [ ]:
np.array([1.3, 1.2, 1.4])

array([1.3, 1.2, 1.4])

2D Array

In [ ]:
x = np.array([[1,2], [-3,1]])

dtype('int64')

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array(
    [[[1,2,3],
     [3,4,5]],

     [[5,6,7],
      [2,3,4]]]
)
x.ndim

3

3D Array do obrazow

Data type


In [ ]:
a = np.array([1,2,3], dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

Tworzenie tablicy

In [4]:
np.zeros(shape=(4,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones(shape=(5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full(shape=(5,5), fill_value=4, dtype=int)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(start=10, stop = 200, step = 10 )

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [13]:
np.linspace(start=0, stop=1000, num=11)

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

In [18]:
a = np.arange(0,15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a.reshape(3,-1)
a.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [22]:
a = np.array([3,1,3,4])
b = np.array([2,2,2,2])
print(a)
print(b)

[3 1 3 4]
[2 2 2 2]


In [23]:
a + b

array([5, 3, 5, 6])

In [33]:
np.add(a, b)

array([5, 3, 5, 6])

In [24]:
a - b

array([ 1, -1,  1,  2])

In [34]:
np.subtract(a, b)

array([ 1, -1,  1,  2])

In [25]:
a * b

array([6, 2, 6, 8])

In [35]:
np.multiply(a, b)

array([6, 2, 6, 8])

In [26]:
a / b

array([1.5, 0.5, 1.5, 2. ])

In [36]:
np.divide(a, b)

array([1.5, 0.5, 1.5, 2. ])

In [27]:
a + 3

array([6, 4, 6, 7])

In [28]:
2 * a

array([6, 2, 6, 8])

In [29]:
a + 3*b

array([ 9,  7,  9, 10])

In [31]:
print(a)

[3 1 3 4]


In [38]:
x = np.array([[2,2],[3,3]])
y = np.array([[1,1],[5,5]])
print(x, '\n')
print(y)

[[2 2]
 [3 3]] 

[[1 1]
 [5 5]]


Mnozenie macierzy

In [39]:
x * y

array([[ 2,  2],
       [15, 15]])

In [40]:
np.dot(x, y)

array([[12, 12],
       [18, 18]])

In [41]:
x.dot(y)

array([[12, 12],
       [18, 18]])

In [42]:
y.dot(x)

array([[ 5,  5],
       [25, 25]])

In [43]:
x @ y

array([[12, 12],
       [18, 18]])

Liczby pseudolosowe

In [44]:
np.random.seed(0)

In [48]:
np.random.randn()

2.240893199201458

In [49]:
np.random.randn(10)

array([ 1.86755799, -0.97727788,  0.95008842, -0.15135721, -0.10321885,
        0.4105985 ,  0.14404357,  1.45427351,  0.76103773,  0.12167502])

In [50]:
np.random.randn(4,10)

array([[ 0.44386323,  0.33367433,  1.49407907, -0.20515826,  0.3130677 ,
        -0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
         1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985, -0.38732682,
        -0.30230275, -1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036, -1.61389785,
        -0.21274028, -0.89546656,  0.3869025 , -0.51080514, -1.18063218]])

In [53]:
np.random.rand()

0.8379449074988039

In [54]:
np.random.rand(10,2)

array([[0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ]])

In [59]:
np.random.randint(10)

0

In [61]:
np.random.randint(low = 10, high=100, size=5)

array([64, 10, 48, 29, 56])

In [69]:
np.random.choice([1,2,3,4,5])

4

In [71]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.random.shuffle(data)
data

array([7, 5, 4, 0, 8, 1, 3, 2, 9, 6])

Podstawowe funkcje

Stala Eulera

In [74]:
np.exp(1)

2.718281828459045

In [75]:
np.sqrt(9)

3.0

In [76]:
np.all([0,1,2])

False

In [77]:
np.any([0,1,2])

True

In [78]:
A = np.random.randn(5)
A

array([ 0.90751962, -0.58582287,  0.93755884, -0.25460809,  0.97359871])

In [80]:
np.argmax(A)

4

In [81]:
np.argsort(A)

array([1, 3, 0, 2, 4])

In [82]:
np.mean(A)

0.39564924103606786

Indeksowanie i wycinanie tablic

In [83]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[index], A[start:stop], A[:stop], A[start:]

In [84]:
A[2]

2

In [85]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [86]:
A[:2]

array([0, 1])

In [88]:
A[[0,2]]

array([0, 2])

In [90]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
A[0]

array([0, 1, 2, 3, 4])

In [92]:
A[:, 0]

array([ 0,  5, 10, 15])

In [93]:
A[1,3]

8

In [101]:
A[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [103]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [105]:
for item in A.flat:
  pass
#ouput 1/n 2/n etc

In [106]:
A.shape

(4, 5)

In [107]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [108]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [109]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maska logiczna

In [113]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [114]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [115]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [116]:
np.bitwise_and(A > -5 , a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [118]:
A[np.bitwise_and(A > -5 , a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])